all:
  hosts:
    mysql:
  children:
    dbservers:
      hosts:
        mysql-1:
          ansible_host: 51.250.103.119
          master: true
        mysql-2:
          ansible_host: 51.250.108.99
          master: false
      vars:
        master_ip: 10.129.0.81
        slave_ip: 10.129.0.82
