---

- include_tasks: mysql_secure_installation.yml
  when: not skip_task
- include_tasks: mysql_change_settings.yml
  when: not skip_task
- include_tasks: mysql_create_cluster.yml
  when: create_claster

...

