---

- include_tasks: mysql_secure_installation.yaml
  when: not skip_task
- include_tasks: mysql_change_settings.yaml
  when: not skip_task
- include_tasks: mysql_create_cluster.yaml
  when: create_claster
- include_tasks: mysql_users_management.yaml
  when: not skip_task
- include_tasks: mysql_cron_management.yaml
  # when: not skip_task

...

