---
- include: mysql_secure_installation.yml

###
- name: "Copy config file"
  ansible.builtin.template: 
    src: 90-ansible.cnf.j2
    dest: /etc/mysql/mariadb.conf.d/90-ansible.cnf
    owner: root
    group: root
    mode: '0644'
  become: yes
  notify:
  - Restart Mariadb Service
  when: not skip_task

...

