---
- include_tasks: mysql_secure_installation.yml

###
- name: "Copy config file"
  ansible.builtin.template: 
    src: 90-ansible.cnf.j2
    dest: /etc/mysql/mariadb.conf.d/90-ansible.cnf
    owner: root
    group: root
    mode: '0644'
  become: yes
  notify:
  - Restart Mariadb Service
  when: not skip_task

- name: Make runtime settings
  mysql_variables:
    variable: "{{ item.variable }}"
    value: "{{ item.value }}"
  loop: "{{ runtime_settings }}"
  become: yes
  when: not skip_task

- name: Get primary binlog file name and binlog position
  community.mysql.mysql_replication:
    mode: getprimary
  become: yes
...

