---
- include_tasks: mysql_secure_installation.yml
  when: not skip_task
- include_tasks: mysql_change_settings.yml
  when: not skip_task

- name: "Set bind-address"
  ansible.builtin.lineinfile:
    path: /etc/mysql/mariadb.conf.d/50-server.cnf
    search_string: 'bind-address'
    line: "bind-address            = 0.0.0.0"
  become: yes
  when: not skip_task

- name: "Set server-id"
  ansible.builtin.lineinfile:
    path: /etc/mysql/mariadb.conf.d/50-server.cnf
    search_string: 'server-id'
    line: "server-id              = 1"
  become: yes
  when: master
  when: not skip_task

- name: "Set server-id"
  ansible.builtin.lineinfile:
    path: /etc/mysql/mariadb.conf.d/50-server.cnf
    search_string: 'server-id'
    line: "server-id              = 2"
  become: yes
  when: not master
  when: not skip_task

- name: "Set log_bin"
  ansible.builtin.lineinfile:
    path: /etc/mysql/mariadb.conf.d/50-server.cnf
    search_string: 'log_bin'
    line: "log_bin                = /var/log/mysql/mysql-bin.log"
  become: yes
  when: not skip_task
  when: not skip_task

- name: "Restart Mariadb Service"
  ansible.builtin.service:
    name: mariadb
    state: restarted
  become: yes
  when: not skip_task

- name: "Create user slave"
  community.mysql.mysql_user: 
    user: "slave" 
    password: 'slave4!' 
    host: '172.31.1.82'
    state: "present"
    priv: '*.*:REPLICATION SLAVE'
  become: yes
  when: master
  when: not skip_task

- name: "Create user root@slave"
  community.mysql.mysql_user: 
    user: "root" 
    password: "{{ mariadb_root_password }}" 
    host: '172.31.1.82'
    state: "present"
    priv: '*.*:ALL,GRANT'
  become: yes
  when: master
  when: not skip_task

- name: "FLUSH PRIVILEGES"
  ansible.builtin.shell: 'mysql --execute="FLUSH PRIVILEGES;"'
  become: yes
  when: master
  when: not skip_task

- name: "FLUSH TABLES WITH READ LOCK"
  ansible.builtin.shell: 'mysql --execute="FLUSH TABLES WITH READ LOCK;"'
  become: yes
  when: master
  when: not skip_task
 
- name: "mysqldump"
  ansible.builtin.shell: 'mysqldump --all-databases --master-data > {{ work_dir}}/data.sql'
  become: yes
  when: master
  when: not skip_task
 
- name: "UNLOCK TABLES"
  ansible.builtin.shell: 'mysql --execute="UNLOCK TABLES;"'
  become: yes
  when: master
  when: not skip_task
 
- name: "save backup from master"
  ansible.builtin.fetch:
    src: "{{ work_dir}}/data.sql"
    dest: /tmp/data.sql
    flat: yes
  become: yes
  when: master
  when: not skip_task
 
- name: "copy backup to slave"
  ansible.builtin.copy:
    src: "/tmp/data.sql"
    dest: "{{ work_dir }}/data.sql"
  become: yes
  when: not skip_task

- name: "STOP SLAVE;"
  ansible.builtin.shell: mysql --execute="STOP SLAVE;"
  become: yes
  when: not master
  # when: not skip_task

- name: "mysql restore backup"
  ansible.builtin.shell: 'mysql < {{ work_dir }}/data.sql'
  become: yes
  when: not master
  when: not skip_task

- name: Get primary binlog file name and binlog position
  community.mysql.mysql_replication:
    mode: getprimary
    login_host: '172.31.1.81'
    login_user: 'root'
    login_password: 'simple4!'
  become: yes
  register: master_params
  when: not master
  when: not skip_task

- name: Print primary binlog file name and binlog position
  ansible.builtin.debug:
    var: master_params.File
  when: not master
  when: not skip_task

- name: Print primary binlog file name and binlog position
  ansible.builtin.debug:
    var: master_params.Position
  when: not master
  when: not skip_task

- name: "CHANGE MASTER"
  ansible.builtin.shell: # mysql --execute='CHANGE MASTER TO MASTER_HOST="172.31.1.81", MASTER_USER="slave", MASTER_PASSWORD="slave4!", MASTER_LOG_FILE="mysql-bin.000002", MASTER_LOG_POS=2128;'
    cmd: |
      mysql <<EOF
      CHANGE MASTER TO MASTER_HOST="172.31.1.81", MASTER_USER="slave", MASTER_PASSWORD="slave4!", MASTER_LOG_FILE="mysql-bin.000002", MASTER_LOG_POS=2128;
      EOF
  become: yes
  when: not master
        
- name: "START SLAVE;"
  ansible.builtin.shell: mysql --execute="START SLAVE;"
  become: yes
  when: not master
  # when: not skip_task

...

