---

- name: "Copy config file"
  ansible.builtin.template: 
    src: 90-ansible.cnf.j2
    dest: /etc/mysql/mariadb.conf.d/90-ansible.cnf
    owner: root
    group: root
    mode: '0644'
  become: yes
  notify:
  - Restart Mariadb Service

- name: Make runtime settings
  mysql_variables:
    variable: "{{ item.variable }}"
    value: "{{ item.value }}"
  loop: "{{ runtime_settings }}"
  become: yes

...