---
- name: "Copy .my.cnf file with root password credentials"
  ansible.builtin.template: 
    src: my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    group: root
    mode: '0600'
  become: yes

- name: "Setup root password"
  community.mysql.mysql_user:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: root
    password: '{{ mariadb_root_password }}'
    host_all: true
  become: yes

- name: Deletes anonymous MySQL server user for ansible_fqdn
  community.mysql.mysql_user: 
    user="" host="{{ ansible_fqdn }}" 
    state="absent"
  become: yes

- name: Deletes anonymous MySQL server user for localhost
  community.mysql.mysql_user: 
    user: "" 
    state: "absent"
  become: yes

- name: Secures the MySQL root user for IPV6 localhost (::1)
  community.mysql.mysql_user: 
    user: "root"
    host: "::1" 
    state: "absent"
  become: yes

- name: Secures the MySQL root user for IPV4 localhost (127.0.0.1)
  community.mysql.mysql_user: 
    user: "root" 
    host: "127.0.0.1"
    state: "absent"
  become: yes

- name: Secures the MySQL root user for localhost domain (localhost)
  community.mysql.mysql_user: 
    user: "root" 
    password: "{{ mariadb_root_password }}" 
    host: "localhost"
  become: yes

- name: Secures the MySQL root user for server_hostname domain
  community.mysql.mysql_user: 
    user: "root" 
    password: "{{ mariadb_root_password }}" 
    host: "{{ ansible_fqdn }}"
    state: "absent"
  become: yes

- name: Removes the MySQL test database
  community.mysql.mysql_db: 
    db: test 
    state: absent
  become: yes

...